# This is a basic workflow to help you get started with Actions

name: App CI/CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
            node-version: 16
      # Install dependecies
      - name: Install project dependencies
        run: npm install

      # Runs unit tests
      - name: Runs unit tests
        run: npm test

      # Runs e2e tests
      - name: Runs e2e tests
        run: npm run test:e2e

      # Deploy the app to heroku
      - name: Deploy app to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12 # action for heroku deployment
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "jim-seenons-api" # Must be unique in Heroku
          heroku_email: ${{secrets.HEROKU_EMAIL}}
